### ISSUE TITLE
implement tab-completion for Lmod, incl. 2nd operand

### ISSUE THREAD

**Issue by fgeorgatos** [plabrop/bic#36]
ie. consider the info near: TACC/Lmod#2
related: TACC/Lmod#144 (ie, cause might be Lmod/zsh interaction)

**Comment by fgeorgatos** [comment]
ie. consider the info near: https://github.com/TACC/Lmod/issues/2

**Comment by fgeorgatos** [comment]
related: https://github.com/TACC/Lmod/issues/144 (ie, cause might be Lmod/zsh interaction)

**Comment by fgeorgatos** [comment]
Just to mention, that EPEL's older Lmod/6.3.4 works fine, as regards this:

```
[root@node002 ~]# lsb_release -d
Description:    CentOS release 6.8 (Final)
[root@node002 ~]# yum info Lmod
Loaded plugins: fastestmirror, priorities
Loading mirror speeds from cached hostfile
 * base: mirrors.tummy.com
 * epel: mirror.prgmr.com
 * extras: centos-distro.cavecreek.net
 * updates: mirror.scalabledns.com
42 packages excluded due to repository priority protections
Installed Packages
Name        : Lmod
Arch        : x86_64
Version     : 6.3.4
Release     : 1.el6
Size        : 929 k
Repo        : installed
From repo   : epel
Summary     : Environmental Modules System in Lua
URL         : https://www.tacc.utexas.edu/tacc-projects/lmod
License     : MIT and LGPLv2
Description : Lmod is a Lua based module system that easily handles the MODULEPATH
            : Hierarchical problem.  Environment Modules provide a convenient way to
            : dynamically change the users' environment through modulefiles. This includes
            : easily adding or removing directories to the PATH environment variable.
            : Modulefiles for library packages provide environment variables that specify
            : where the library and header files can be found.
```

**Comment by pneerincx** [comment]
EPEL's older Lmod/6.3.4 does not work completely for us anymore, but an older 6.0.15 does. In 6.3.4 completion of commands (1st argument) works, but completion of the second argument does not work anymore. We use LMOD_REDIRECT='True' to get the output from commands like module list, module avail, etc. in STDOUT instead of STDERR, but in init/lmod_bash_completions STDOUT is hardcoded to /dev/null. Looks like this was the case in the older 6.0.15 too, but apparently the LMOD_REDIRECT environment variable was ignored for autocompletion...

**Comment by fgeorgatos** [comment]
@pneerincx : thanks for the above feedback, as well as the work that end up in the Lmod/6.5.8+ releases!

**Comment by fgeorgatos** [comment]
this has been handled by PR #52, closing!
